### ISSUE TITLE
Too many Pycom Console terminals are created which can not be killed

### ISSUE THREAD

**Issue by choeffer** [pycom/pymakr-vsc#47]
## What are the steps to reproduce this issue?

1. Open VSC
2. Connect LoPy4 + Pytrack board vis USB
3. Run different commands from the pymakr plugin

## What happens?

More than one _Pycom Console_  is created but they can not be closed. If trying to close them via the _Kill Terminal_ button in VSC in the right down corner, they get recreated even if they do not have any use.

## What were you expecting to happen?

Just one _Pycom Terminal_ should be created.

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

![temp3](https://user-images.githubusercontent.com/33625292/57623341-da9ce800-758f-11e9-9514-edf3a4818525.png)
![temp2](https://user-images.githubusercontent.com/33625292/57623342-db357e80-758f-11e9-81f2-904a8e1dbbf2.png)
![temp1](https://user-images.githubusercontent.com/33625292/57623344-db357e80-758f-11e9-81d7-44cc047f3928.png)
![temp](https://user-images.githubusercontent.com/33625292/57623345-db357e80-758f-11e9-91a5-7d1b65d0290f.png)

## What versions of software are you using?

**Operating system: Debian Buster all updates installed**

**VSCode version: 1.33.1**

**Pymakr version: 1.1.0**

**Comment by osechet** [comment]
If it can help, I found an easy way to reproduce:
1. Open vscode and wait for the first Pycom console to open
2. Open a "standard" vscode terminal by pressing the '+' button
3. Kill the "standard" terminal
=> a new Pycom console opens that cannot be killed.

**Comment by RalphHogenbirk** [comment]
Thanks for this report, and @osechet for the hint that made me find the issue. Turns out the 'onClose' callback from the vscode.terminal API was not checking if the closed console was actually the Pycom console or another one. I've pushed a fix to the develop branch now. Now it just restarts the Pycom Console when it's closed, not when any other terminals are closed. It'll be included in the next release

**Comment by Josverl** [comment]
thanks for finding (and fixing) this , I ran into it all the time but never found the repro steps ...

**Comment by romzes13** [comment]
The issue is still there. Somehow Pycom Console just wont die. Tried killing it in VS code and restarting IDE without success.
Every time I start/restart my IDE the console opens up and tries to connect to USB
```
AutoConnect enabled, ignoring 'address' setting (see Global Settings)
Searching for PyCom boards on serial...
No PyCom boards found on USB``` 

I should probably add a new issue.

**Comment by Josverl** [comment]
@romzes13 if pymakr is enabled , it will always create a terminal.
as i use vscode all day long, and pymakr only for personal work sometimes it does get in the way. ( as is the case with some of the other 60 extensions i use. 
i make use vscode`s configuration options to deal with this 

- pymakr is installed , but disabled globally (1 tmie action) 
- for each micropython prject I enable it for that folder / workspace ( 1 time action per folder / project) 
![image](https://user-images.githubusercontent.com/981654/84240155-e2fe8400-aafd-11ea-94bd-da90e39d4dae.png)

and it works where I want it , and does not get in the way in any other project
